name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Audio Dependency install (ALSA)
      run: sudo apt-get -y install libasound2-dev
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build debug
        run: cargo build --verbose
      - name: Build release
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
    
